apiVersion: v1
kind: Secret
metadata:
  namespace: kubegraf
  name: grafana-kubegraf-secret
  annotations:
    kubernetes.io/service-account.name: grafana-kubegraf
type: kubernetes.io/service-account-token
